version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
      - "8501:8501"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/resume_parser
      - API_BASE_URL=http://0.0.0.0:8000
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=resume_parser
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge