# Streamlit server configuration for hosted environments (e.g., HF Spaces)
# Adjusts upload handling to avoid proxy/XSRF-related 403s on /_stcore/upload_file

[server]
enableStaticServing = false
enableCORS = true
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"

# Disable problematic features that might require the missing JS
[theme]
base = "light"

[logger]
level = "error"
