# Streamlit server configuration for hosted environments (e.g., HF Spaces)
# Adjusts upload handling to avoid proxy/XSRF-related 403s on /_stcore/upload_file

[server]
enableStaticServing = false
enableCORS = true
enableXsrfProtection = false
headless = true
port = 8501

# ADD THIS - Fix the CORS issue by explicitly allowing your domain
corsAllowedOrigins = [
    "https://youssef2106-ai-resume-parser.hf.space",
    "https://devel.streamlit.test",
    "https://*.streamlit.apptest", 
    "https://*.streamlitapp.test",
    "https://*.streamlitapp.com",
    "https://share.streamlit.io",
    "https://share-demo.streamlit.io",
    "https://share-head.streamlit.io", 
    "https://share-staging.streamlit.io",
    "https://*.demo.streamlit.run",
    "https://*.head.streamlit.run",
    "https://*.staging.streamlit.run",
    "https://*.streamlit.run",
    "https://*.demo.streamlit.app",
    "https://*.head.streamlit.app", 
    "https://*.staging.streamlit.app",
    "https://*.streamlit.app"
]

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"

# Disable problematic features that might require the missing JS
[theme]
base = "light"

[logger]
level = "error"